spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}


  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret_key: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

flutterwave:
  public-key: ${FLUTTER_KEY}
  secret-key: ${FLUTTER_SECRET}
  encryption-key: ${FLUTTER_ENCRYPTION}
  base-url: ${FLUTTER_BAE_URL}

